# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 19:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('truncated', models.TextField(null=True)),
                ('quote_count', models.IntegerField(null=True)),
                ('reply_count', models.IntegerField(null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('favorite_count', models.IntegerField(null=True)),
                ('favorited', models.BooleanField(default=0)),
                ('retweeted', models.BooleanField(default=0)),
                ('hashtags', models.TextField(null=True)),
                ('media', models.TextField(null=True)),
                ('symbols', models.TextField(null=True)),
                ('urls', models.TextField(null=True)),
                ('user_mentions', models.TextField(null=True)),
                ('extended_entities', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'streams',
            },
        ),
        migrations.CreateModel(
            name='StreamUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('screen_name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.Stream')),
            ],
            options={
                'db_table': 'stream_users',
            },
        ),
    ]
